### ISSUE TITLE
Exception java.lang.OutOfMemoryError: Failed to allocate a 85442828 byte allocation with 4193440 free bytes and 68MB until OOM

### ISSUE THREAD

**Issue by petrovichtim** [JetradarMobile/desertplaceholder#11]
Пришло 8 отчетов с ошибкой в версии 1.2.4
`
Exception java.lang.OutOfMemoryError: Failed to allocate a 85442828 byte allocation with 4193440 free bytes and 68MB until OOM
dalvik.system.VMRuntime.newNonMovableArray (VMRuntime.java)
android.graphics.Bitmap.nativeCreate (Bitmap.java)
android.graphics.Bitmap.createBitmap (Bitmap.java:831)
android.graphics.Bitmap.createBitmap (Bitmap.java:808)
android.graphics.Bitmap.createBitmap (Bitmap.java:739)
android.graphics.Bitmap.createScaledBitmap (Bitmap.java:615)
com.jetradar.desertplaceholder.TumbleweedView.drawShadow (TumbleweedView.java:119)
com.jetradar.desertplaceholder.TumbleweedView.onDraw (TumbleweedView.java:95)
android.view.View.draw (View.java:16456)
android.view.View.updateDisplayListIfDirty (View.java:15409)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3719)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3699)
android.view.View.updateDisplayListIfDirty (View.java:15360)
android.view.View.draw (View.java:16210)
android.view.ViewGroup.drawChild (ViewGroup.java:3735)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3525)
android.view.View.draw (View.java:16468)
android.view.View.updateDisplayListIfDirty (View.java:15409)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3719)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3699)
android.view.View.updateDisplayListIfDirty (View.java:15360)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3719)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3699)
android.view.View.updateDisplayListIfDirty (View.java:15360)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3719)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3699)
android.view.View.updateDisplayListIfDirty (View.java:15360)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3719)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3699)
android.view.View.updateDisplayListIfDirty (View.java:15360)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3719)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3699)
android.view.View.updateDisplayListIfDirty (View.java:15360)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3719)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3699)
android.view.View.updateDisplayListIfDirty (View.java:15360)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3719)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3699)
android.view.View.updateDisplayListIfDirty (View.java:15360)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3719)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3699)
android.view.View.updateDisplayListIfDirty (View.java:15360)
android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:286)
android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:292)
android.view.ThreadedRenderer.draw (ThreadedRenderer.java:327)
android.view.ViewRootImpl.draw (ViewRootImpl.java:3020)
android.view.ViewRootImpl.performDraw (ViewRootImpl.java:2824)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2436)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1321)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6708)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:894)
android.view.Choreographer.doCallbacks (Choreographer.java:696)
android.view.Choreographer.doFrame (Choreographer.java:631)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:880)
android.os.Handler.handleCallback (Handler.java:815)
android.os.Handler.dispatchMessage (Handler.java:104)
android.os.Looper.loop (Looper.java:207)
android.app.ActivityThread.main (ActivityThread.java:5728)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:789)`

**Comment by johnkil** [comment]
кек

**Comment by petrovichtim** [comment]
ещё один в крешлитик сегодня прилетел
`Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:669)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:615)
       at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:495)
       at com.jetradar.desertplaceholder.TumbleweedView.drawShadow(SourceFile:119)
       at com.jetradar.desertplaceholder.TumbleweedView.onDraw(SourceFile:95)
       at android.view.View.draw(View.java:13614)
       at android.view.View.getDisplayList(View.java:12565)
       at android.view.View.getDisplayList(View.java:12609)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2972)
       at android.view.View.getDisplayList(View.java:12501)
       at android.view.View.getDisplayList(View.java:12609)
       at android.view.View.draw(View.java:13338)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.draw(View.java:13617)
       at android.widget.FrameLayout.draw(FrameLayout.java:467)
       at android.view.View.getDisplayList(View.java:12565)
       at android.view.View.getDisplayList(View.java:12609)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2972)
       at android.view.View.getDisplayList(View.java:12501)
       at android.view.View.getDisplayList(View.java:12609)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2972)
       at android.view.View.getDisplayList(View.java:12501)
       at android.view.View.getDisplayList(View.java:12609)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2972)
       at android.view.View.getDisplayList(View.java:12501)
       at android.view.View.getDisplayList(View.java:12609)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2972)
       at android.view.View.getDisplayList(View.java:12501)
       at android.view.View.getDisplayList(View.java:12609)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2972)
       at android.view.View.getDisplayList(View.java:12501)
       at android.view.View.getDisplayList(View.java:12609)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2972)
       at android.view.View.getDisplayList(View.java:12501)
       at android.view.View.getDisplayList(View.java:12609)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2972)
       at android.view.View.getDisplayList(View.java:12501)
       at android.view.View.getDisplayList(View.java:12609)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2972)
       at android.view.View.getDisplayList(View.java:12501)
       at android.view.View.getDisplayList(View.java:12609)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1187)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2313)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2185)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1993)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1143)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4674)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4960)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by petrovichtim** [comment]
Вот ещё облока тупят 
`Fatal Exception: java.lang.NullPointerException
       at com.jetradar.desertplaceholder.CloudsView.initClouds(SourceFile:85)
       at com.jetradar.desertplaceholder.CloudsView.onDraw(SourceFile:67)
       at android.view.View.draw(View.java:14482)
       at android.view.View.getDisplayList(View.java:13379)
       at android.view.View.getDisplayList(View.java:13421)
       at android.view.View.draw(View.java:14199)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
       at android.view.View.draw(View.java:14485)
       at android.view.View.getDisplayList(View.java:13379)
       at android.view.View.getDisplayList(View.java:13421)
       at android.view.View.draw(View.java:14199)`

**Comment by johnkil** [comment]
😢
