### ISSUE TITLE
Bug on some devices

### ISSUE THREAD

**Issue by petrovichtim** [JetradarMobile/desertplaceholder#7]
Device : Galaxy J7(2016) (j7xelte)
Library version 1.2.1
`
java.lang.IllegalArgumentException: 
  at android.graphics.Bitmap.createBitmap(Bitmap.java:967)
  at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
  at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
  at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:753)
  at com.jetradar.desertplaceholder.TumbleweedView.drawShadow(TumbleweedView.java:116)
  at com.jetradar.desertplaceholder.TumbleweedView.onDraw(TumbleweedView.java:95)
  at android.view.View.draw(View.java:17503)
  at android.view.View.updateDisplayListIfDirty(View.java:16496)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
  at android.view.View.updateDisplayListIfDirty(View.java:16456)
  at android.view.View.draw(View.java:17272)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
  at android.view.View.draw(View.java:17506)
  at android.view.View.updateDisplayListIfDirty(View.java:16496)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
  at android.view.View.updateDisplayListIfDirty(View.java:16456)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
  at android.view.View.updateDisplayListIfDirty(View.java:16456)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
  at android.view.View.updateDisplayListIfDirty(View.java:16456)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
  at android.view.View.updateDisplayListIfDirty(View.java:16456)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
  at android.view.View.updateDisplayListIfDirty(View.java:16456)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
  at android.view.View.updateDisplayListIfDirty(View.java:16456)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
  at android.view.View.updateDisplayListIfDirty(View.java:16456)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
  at android.view.View.updateDisplayListIfDirty(View.java:16456)
  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
  at android.view.ViewRootImpl.draw(ViewRootImpl.java:3144)
  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2943)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2525)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1440)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7421)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
  at android.view.Choreographer.doCallbacks(Choreographer.java:695)
  at android.view.Choreographer.doFrame(Choreographer.java:631)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:158)
  at android.app.ActivityThread.main(ActivityThread.java:7230)
  at java.lang.reflect.Method.invoke(Method.java:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
`

**Comment by petrovichtim** [comment]
**version 1.2.2**
Exception java.lang.IllegalArgumentException: width and height must be > 0
android.graphics.Bitmap.createBitmap (Bitmap.java:810)
android.graphics.Bitmap.createBitmap (Bitmap.java:789)
android.graphics.Bitmap.createBitmap (Bitmap.java:720)
android.graphics.Bitmap.createScaledBitmap (Bitmap.java:596)
com.jetradar.desertplaceholder.TumbleweedView.a (SourceFile:116)
com.jetradar.desertplaceholder.TumbleweedView.onDraw (SourceFile:95)
android.view.View.draw (View.java:15497)
android.view.View.updateDisplayListIfDirty (View.java:14386)
android.view.View.getDisplayList (View.java:14415)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3527)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3506)
android.view.View.updateDisplayListIfDirty (View.java:14336)

**Comment by petrovichtim** [comment]
java.lang.IllegalArgumentException: 
  at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
  at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
  at android.graphics.Bitmap.createBitmap(Bitmap.java:720)
  at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:596)
  at com.jetradar.desertplaceholder.TumbleweedView.drawShadow(TumbleweedView.java:116)
  at com.jetradar.desertplaceholder.TumbleweedView.onDraw(TumbleweedView.java:95)
  at android.view.View.draw(View.java:15497)
  at android.view.View.updateDisplayListIfDirty(View.java:14386)
  at android.view.View.getDisplayList(View.java:14415)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3527)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3506)
  at android.view.View.updateDisplayListIfDirty(View.java:14336)
  at android.view.View.getDisplayList(View.java:14415)
  at android.view.View.draw(View.java:15206)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3543)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3330)
  at android.view.View.draw(View.java:15509)
  at android.widget.FrameLayout.draw(FrameLayout.java:658)
  at android.view.View.updateDisplayListIfDirty(View.java:14386)
  at android.view.View.getDisplayList(View.java:14415)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3527)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3506)
  at android.view.View.updateDisplayListIfDirty(View.java:14336)
  at android.view.View.getDisplayList(View.java:14415)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3527)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3506)
  at android.view.View.updateDisplayListIfDirty(View.java:14336)
  at android.view.View.getDisplayList(View.java:14415)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3527)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3506)
  at android.view.View.updateDisplayListIfDirty(View.java:14336)
  at android.view.View.getDisplayList(View.java:14415)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3527)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3506)
  at android.view.View.updateDisplayListIfDirty(View.java:14336)
  at android.view.View.getDisplayList(View.java:14415)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3527)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3506)
  at android.view.View.updateDisplayListIfDirty(View.java:14336)
  at android.view.View.getDisplayList(View.java:14415)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3527)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3506)
  at android.view.View.updateDisplayListIfDirty(View.java:14336)
  at android.view.View.getDisplayList(View.java:14415)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3527)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3506)
  at android.view.View.updateDisplayListIfDirty(View.java:14336)
  at android.view.View.getDisplayList(View.java:14415)
  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3527)
  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3506)
  at android.view.View.updateDisplayListIfDirty(View.java:14336)
  at android.view.View.getDisplayList(View.java:14415)
  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:279)
  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:285)
  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:335)
  at android.view.ViewRootImpl.draw(ViewRootImpl.java:2939)
  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2753)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1292)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6614)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
  at android.view.Choreographer.doCallbacks(Choreographer.java:603)
  at android.view.Choreographer.doFrame(Choreographer.java:572)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
  at android.os.Handler.handleCallback(Handler.java:815)
  at android.os.Handler.dispatchMessage(Handler.java:104)
  at android.os.Looper.loop(Looper.java:194)
  at android.app.ActivityThread.main(ActivityThread.java:5640)
  at java.lang.reflect.Method.invoke(Method.java:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
